language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
before_install:
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then yes | pecl install -f apcu; fi
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apcu.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apcu.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install
